gcp:
  project_id: zsc-personal
  region: us-east1
  gcs:
    buckets:
      - name: ml-cloud-project-gcs
        paths:
          data: data/papers
          embeddings: data/embeddings
          fine_tune: 
            models: fine_tune/models
            data: fine_tune/data
  gke:
    cluster_name: gke-cluster-ml-cloud
    service_account_name: gke-ml-cloud-service-account
    machine_type: e2-standard-2
    services:
      kubeflow:
        images: 
          cpu: us-east1-docker.pkg.dev/zsc-personal/pdf-fusion/ml-cloud-pipeline-cpu
          gpu: us-east1-docker.pkg.dev/zsc-personal/pdf-fusion/ml-cloud-pipeline-gpu
        pipeline_path: ./infra/k8s/ml-cloud-pipeline.yaml
        pipeline_name: ml-cloud-pipeline
        experiment_name: ml-cloud-kubeflow-experiment
        host: http://localhost:8080
      arxiv_summarization_api:
        image: us-east1-docker.pkg.dev/zsc-personal/pdf-fusion/arxiv-summarization-api
        ksa_name: arxiv-summarization-api-service-account
        namespace: arxiv-summarization-api
      frontend:
        image: us-east1-docker.pkg.dev/zsc-personal/pdf-fusion/pdf-fusion-frontend
      vector_db:
        namespace: vector-db
        collection_name: arxiv-papers
        url: qdrant.vector-db.svc.cluster.local:6333
dockerfile:
  kubeflow_cpu: Dockerfile.kubeflow-cpu
  kubeflow_gpu: Dockerfile.kubeflow-gpu
  api: Dockerfile.api
  frontend: Dockerfile.frontend
terraform:
  tfvars:
    prod: 
      path: ./infra/terraform/prod.tfvars