FROM python:3.11.2-slim

ARG  BUILDKIT_INLINE_CACHE=1
WORKDIR /app

# Install requirements
RUN python -m pip install --upgrade pip wheel setuptools
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy source code
COPY src/ ./src/

# Copy config file
COPY config.yaml .

ENV PYTHONPATH=/app
