FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender-dev \
    wget \
    && rm -rf /var/lib/apt/lists/*

RUN python -m pip install --upgrade pip wheel setuptools
COPY src/front/requirements.txt .
RUN pip install -r requirements.txt

EXPOSE 8501

COPY src/front/pdfusion_app.py . 
COPY src/front/pdfusion.png . 

CMD ["streamlit", "run", "pdfusion_app.py", "--server.headless", "true"]
