apiVersion: apps/v1
kind: Deployment
metadata:
  name: arxiv-summarization-api-deployment
  namespace: arxiv-summarization-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arxiv-summarization-api
  template:
    metadata:
      labels:
        app: arxiv-summarization-api
    spec:
      serviceAccountName: arxiv-summarization-api-service-account
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Equal"
          value: "present"
          effect: "NoSchedule"
      nodeSelector:
        gpu_pool: "kubeflow"
      containers:
        - name: arxiv-summarization-api
          image: us-east1-docker.pkg.dev/zsc-personal/pdf-fusion/arxiv-summarization-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            limits:
              memory: "8Gi"
              cpu: "1"
              nvidia.com/gpu: 1
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: arxiv-summarization-api-service
  namespace: arxiv-summarization-api
spec:
  selector:
    app: arxiv-summarization-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer