apiVersion: v1
kind: Pod
metadata:
  name: gpu-test-interactive
spec:
  containers:
  - name: cuda-container
    image: nvcr.io/nvidia/cuda:12.1.0-base-ubuntu22.04
    command: ["sleep"]
    args: ["infinity"]
    resources:
      limits:
        nvidia.com/gpu: 1
    env:
    - name: NVIDIA_VISIBLE_DEVICES
      value: "all"
    - name: NVIDIA_DRIVER_CAPABILITIES
      value: "all"
  tolerations:
  - key: "nvidia.com/gpu"
    operator: "Equal"
    value: "present"
    effect: "NoSchedule"