apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdfusion-app
  namespace: arxiv-summarization-api
  labels:
    app: pdfusion-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdfusion-app
  template:
    metadata:
      labels:
        app: pdfusion-app
    spec:
      containers:
        - name: pdfusion
          image: us-east1-docker.pkg.dev/zsc-personal/pdf-fusion/pdf-fusion-frontend:latest
          ports:
            - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: pdfusion-service
  namespace: arxiv-summarization-api
spec:
  selector:
    app: pdfusion-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
